import { Provider as ColorModeProvider } from "@/app/shared/snippets/provider";
import Header from "@/app/shared/header";
import type { Metadata } from "next";
import { Montserrat_Alternates, Questrial } from "next/font/google";
import Footer from "@/app/shared/footer";
import { Toaster } from "./shared/snippets/toaster";
import { SessionProvider } from "next-auth/react";
import { Stack, Container } from "@chakra-ui/react";

const montserrat = Montserrat_Alternates({
  variable: "--font-montserrat-alternates",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const questrial = Questrial({
  variable: "--font-questrial",
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} ${questrial.variable}`}
        style={{
          display: "flex",
          flexDirection: "column",
          height: "100vh",
          maxWidth: "100vw",
          justifyContent: "space-between",
        }}
      >
        <SessionProvider>
          <ColorModeProvider>
            <Toaster />
            <Header />
            <Container
              as="main"
              w="100%"
              maxW="100%"
              flex={1}
              flexDir={"column"}
              alignItems={"stretch"}
              justifyContent={"stretch"}
              py={5}
              px={5}
            >
              <Stack as="section" h="100%" justifyContent={"center"}>
                {children}
              </Stack>
            </Container>
            <Footer />
          </ColorModeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
