import { Provider as ColorModeProvider } from "@/app/shared/components/provider";
import type { Metadata } from "next";
import { Montserrat_Alternates, Questrial, Arvo } from "next/font/google";

const montserrat = Montserrat_Alternates({
  variable: "--font-montserrat-alternates",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const arvo = Arvo({
  variable: "--arvo",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const questrial = Questrial({
  variable: "--font-questrial",
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} ${arvo.variable} ${questrial.variable}`}
      >
        <ColorModeProvider>{children}</ColorModeProvider>
      </body>
    </html>
  );
}
